apollo:
  AppID: "test"
  Cluster: "dev"
  IP: "http://localhost:8080"
  NamespaceName: "application,test.yaml"
  IsBackupConfig: false
  BackupConfigPath: ""
  Secret: ""
  SyncServerTimeout: 0
  MustStart: true
  Watch: true